### PR TITLE
Created german translation texts.

### PR DESCRIPTION
**Pull request by Atomzwieback**
May some of the texts should be updated after i see if they fit correctly for the kind of sitation in the UI.

### CODE REVIEW

**Comment by RetroPronghorn** [comment]
@Atomzwieback Are you comfortable adding this transaltion to the list? I can add it manually if you arnt but simply adding the file will not add it to the dropdown, the `src/config/config.js` needs to be edited as well as `src/utils/i18n.js`

**Comment by Atomzwieback** [comment]
@RetroPronghorn  Sure i can, i will do it tomorrow. Its already late here.

**Comment by Atomzwieback** [comment]
I think it is done now, i uploaded the json to ipfs and added the hash to the config.

**Review by RetroPronghorn — APPROVED** [review]

**Comment by RetroPronghorn** [comment]
Merged, thank you!

**Pull request merged**
